
# Install the needed package of mysql
- name: Install MySQL packages
  apt: pkg={{ item }} state=present
  with_items:
    
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb
    - python3-pip
    - build-essential
- name: pymysql
  become: true
  pip:
    name: pymysql
    state: present

#copy .my.cnf with root password
- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  notify: Restart the MySQL service


- name: Create database user with name 'ttn' and  all database privileges
  become: true
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ttn
    password: "{{ password }}"
    priv: '*.*:ALL'
    state: present
  

