- name: "Copy nginx configuration file"
  copy: 
    dest: /etc/nginx/sites-enabled/default
    src: files/nginx.conf
  
- name: "Copy index.html file"
  copy: 
    dest: /var/www/html
    src: files/index.html
 
  notify: 
    - "restart nginx"

